import React, { useState } from 'react';
import { FeedbackSession, NextStep, Task, Submission } from '../../types';
import { GoalBox } from './GoalBox';
import { Badge } from '../ui/Badge';
import { Button } from '../ui/Button';
import { CheckCircle2, AlertCircle, ArrowRight, CornerDownRight, Sparkles, CheckCircle, Copy, Check } from 'lucide-react';
import { motion } from 'framer-motion';

interface FeedbackViewProps {
  sessionData: FeedbackSession;
  onContinue: (step: NextStep) => void;
  masteryConfirmed?: boolean;
  onComplete?: () => void;
  task?: Task; // For learning notes
  submission?: Submission; // For learning notes
}

export const FeedbackView: React.FC<FeedbackViewProps> = ({
  sessionData,
  onContinue,
  masteryConfirmed = false,
  onComplete,
  task,
  submission
}) => {
  const [selectedStepId, setSelectedStepId] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const selectedStep = sessionData.nextSteps.find(s => s.id === selectedStepId);

  // Format learning notes for clipboard
  const formatLearningNotes = (): string => {
    const lines: string[] = [];

    lines.push('# Learning Notes');
    lines.push('');

    // Task/Learning Question
    if (task) {
      lines.push('## Learning Task');
      lines.push(`**${task.title}**`);
      lines.push('');
      lines.push('### Prompt');
      lines.push(task.prompt);
      lines.push('');
    }

    // Original Response
    if (submission?.content) {
      lines.push('## My Response');
      lines.push(submission.content);
      lines.push('');
    }

    // Feedback
    lines.push('## Feedback Received');
    lines.push('');
    lines.push(`**Goal:** ${sessionData.goal}`);
    lines.push('');

    // Strengths
    lines.push('### What Worked Well');
    sessionData.strengths.forEach(s => {
      lines.push(`- ${s.text}`);
      if (s.anchors && s.anchors.length > 0) {
        lines.push(`  > "${s.anchors[0]}"`);
      }
    });
    lines.push('');

    // Growth Areas
    lines.push('### Areas for Growth');
    sessionData.growthAreas.forEach(g => {
      lines.push(`- ${g.text}`);
      if (g.anchors && g.anchors.length > 0) {
        lines.push(`  > "${g.anchors[0]}"`);
      }
    });
    lines.push('');

    // Next Steps
    lines.push('### Suggested Next Steps');
    sessionData.nextSteps.forEach(step => {
      lines.push(`- **${step.actionVerb}** ${step.target}`);
      lines.push(`  Success looks like: ${step.successIndicator}`);
      if (step.reflectionPrompt) {
        lines.push(`  _Reflect: ${step.reflectionPrompt}_`);
      }
    });
    lines.push('');

    // Revision content if available
    if (submission?.previousContent) {
      lines.push('## Revised Response');
      lines.push(submission.content);
      lines.push('');
    }

    lines.push('---');
    lines.push(`_Generated by EDberg on ${new Date().toLocaleDateString()}_`);

    return lines.join('\n');
  };

  const handleCopyNotes = async () => {
    const notes = formatLearningNotes();
    try {
      await navigator.clipboard.writeText(notes);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 pb-32">
      {/* Principle 1 & 2: Start with the Goal */}
      <GoalBox
        goalText={sessionData.goal}
        universal={false}
      />

      {/* Mastery feedback banner with gold accents */}
      {masteryConfirmed && (
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          className="max-w-xl mx-auto px-4 pt-6"
        >
          <div className="bg-gradient-to-r from-gold-50 to-white border border-gold-200 rounded-xl p-4">
            <div className="flex items-center gap-3">
              <div className="bg-gold-100 p-2 rounded-full">
                <CheckCircle className="w-5 h-5 text-gold-600" />
              </div>
              <p className="text-navy-800 font-medium">
                Your teacher has reviewed your work. See the feedback below.
              </p>
            </div>
          </div>
        </motion.div>
      )}

      <main className="max-w-xl mx-auto px-4 py-6 space-y-6">
        
        {/* Card 1: What's working well */}
        <motion.section 
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
          className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden"
        >
          <div className="px-5 py-4 border-b border-slate-100 flex items-center gap-2.5 bg-gradient-to-r from-emerald-50 to-white">
            <div className="bg-emerald-100 p-1.5 rounded-full text-emerald-600">
                <CheckCircle2 className="w-4 h-4" />
            </div>
            <h2 className="font-semibold text-slate-900 text-sm uppercase tracking-wide">Working Well</h2>
          </div>
          <div className="p-5 space-y-5">
            {sessionData.strengths.map((item) => (
              <div key={item.id} className="relative pl-4 border-l-2 border-emerald-100">
                <div className="mb-1.5">
                   <Badge type={item.type} />
                </div>
                <p className="text-slate-700 text-sm leading-relaxed">
                  {item.text}
                </p>
                {/* Traceability: Show anchor from student work */}
                {item.anchors && item.anchors.length > 0 && (
                   <div className="mt-2 text-xs text-slate-500 bg-emerald-50 p-2.5 rounded-lg border border-emerald-100 italic flex items-start gap-2">
                     <span className="text-emerald-300">❝</span>
                     {item.anchors[0]}
                   </div>
                )}
              </div>
            ))}
          </div>
        </motion.section>

        {/* Card 2: What needs attention */}
        <motion.section 
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4, delay: 0.1 }}
          className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden"
        >
          <div className="px-5 py-4 border-b border-slate-100 flex items-center gap-2.5 bg-gradient-to-r from-amber-50 to-white">
             <div className="bg-amber-100 p-1.5 rounded-full text-amber-600">
                <AlertCircle className="w-4 h-4" />
            </div>
            <h2 className="font-semibold text-slate-900 text-sm uppercase tracking-wide">Needs Focus</h2>
          </div>
          <div className="p-5 space-y-5">
             {sessionData.growthAreas.map((item) => (
              <div key={item.id} className="relative pl-4 border-l-2 border-amber-100">
                <div className="mb-1.5">
                   <Badge type={item.type} />
                </div>
                <p className="text-slate-700 text-sm leading-relaxed">
                  {item.text}
                </p>
                {/* Traceability Requirement: Map to specific work if available */}
                {item.anchors && item.anchors.length > 0 && (
                   <div className="mt-2 text-xs text-slate-500 bg-slate-50 p-2.5 rounded-lg border border-slate-100 italic flex items-start gap-2">
                     <span className="text-slate-300">❝</span>
                     {item.anchors[0]}
                   </div>
                )}
              </div>
            ))}
          </div>
        </motion.section>

        {/* Card 3: Choose One Next Step (Mandatory or Optional based on mastery) */}
        <motion.section
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4, delay: 0.2 }}
          className={`bg-white rounded-2xl shadow-md overflow-hidden ${
            masteryConfirmed
              ? 'shadow-gold-500/10 border border-gold-200 ring-4 ring-gold-50'
              : 'shadow-brand-500/5 border border-brand-100 ring-4 ring-brand-50'
          }`}
        >
          <div className={`px-5 py-4 border-b flex items-center gap-2.5 ${
            masteryConfirmed
              ? 'border-gold-100 bg-gradient-to-r from-gold-50 to-white'
              : 'border-brand-100 bg-gradient-to-r from-brand-50 to-white'
          }`}>
             <div className={`p-1.5 rounded-full ${
               masteryConfirmed
                 ? 'bg-gold-100 text-gold-600'
                 : 'bg-brand-100 text-brand-600'
             }`}>
                {masteryConfirmed ? <Sparkles className="w-4 h-4" /> : <CornerDownRight className="w-4 h-4" />}
            </div>
            <h2 className={`font-semibold text-sm uppercase tracking-wide ${
              masteryConfirmed ? 'text-navy-800' : 'text-brand-900'
            }`}>
              {masteryConfirmed ? 'Challenge Yourself (Optional)' : 'Select Next Step'}
            </h2>
          </div>
          <div className={`p-2 ${masteryConfirmed ? 'bg-gold-50/30' : 'bg-brand-50/10'}`}>
            <p className="px-4 pt-3 pb-2 text-xs text-slate-500 font-medium">
              {masteryConfirmed
                ? 'Want to push yourself further? Try one of these optional challenges:'
                : 'Choose the action you will take to improve your work:'}
            </p>
            <div className="space-y-2 p-2">
              {sessionData.nextSteps.map((step) => (
                <label 
                  key={step.id}
                  className={`group relative flex items-start gap-4 p-4 rounded-xl border cursor-pointer transition-all duration-200 ${
                    selectedStepId === step.id 
                      ? 'bg-brand-50 border-brand-500 shadow-sm' 
                      : 'bg-white border-slate-200 hover:border-brand-200 hover:shadow-sm'
                  }`}
                >
                  <div className={`mt-0.5 w-5 h-5 rounded-full border flex items-center justify-center transition-colors ${
                      selectedStepId === step.id ? 'border-brand-600 bg-brand-600 text-white' : 'border-slate-300 group-hover:border-brand-300'
                  }`}>
                      {selectedStepId === step.id && <div className="w-2 h-2 bg-white rounded-full" />}
                  </div>
                  <input 
                    type="radio" 
                    name="nextStep"
                    value={step.id}
                    checked={selectedStepId === step.id}
                    onChange={() => setSelectedStepId(step.id)}
                    className="sr-only" // Visually hidden but accessible
                  />
                  <div className="flex-1">
                    <p className="font-medium text-slate-900 text-sm leading-snug">
                      <span className="text-brand-700 font-bold">{step.actionVerb}</span> {step.target}
                    </p>
                    <div className="flex items-center gap-1.5 mt-2 text-xs text-slate-500 bg-white/50 inline-flex px-2 py-1 rounded border border-slate-100">
                        <Sparkles className="w-3 h-3 text-brand-400" />
                        {step.successIndicator}
                    </div>
                    {step.reflectionPrompt && (
                      <p className="mt-2 text-sm text-slate-500 italic bg-slate-50 p-2 rounded">
                        <span className="font-medium not-italic">Reflect:</span> {step.reflectionPrompt}
                      </p>
                    )}
                  </div>
                </label>
              ))}
            </div>
          </div>
        </motion.section>
      </main>

      {/* Floating Action Bar - Mobile First Sticky Footer */}
      <div className="fixed bottom-0 left-0 right-0 p-4 bg-white/90 backdrop-blur-md border-t border-slate-200 shadow-lg z-50">
        <div className="max-w-xl mx-auto space-y-2">
          {masteryConfirmed ? (
            <>
              {/* Primary: Finish button - neutral language */}
              <Button
                className="w-full h-12 text-base font-semibold tracking-wide"
                size="lg"
                variant="primary"
                onClick={onComplete}
                leftIcon={<CheckCircle className="w-5 h-5" />}
              >
                Finish
              </Button>
              {/* Secondary: Optional next step */}
              {selectedStepId && selectedStep && (
                <Button
                  className="w-full h-10 text-sm font-medium"
                  size="md"
                  variant="outline"
                  onClick={() => onContinue(selectedStep)}
                  leftIcon={<Sparkles className="w-4 h-4" />}
                >
                  Optional: {selectedStep.ctaText}
                </Button>
              )}
              {/* Copy to Learning Notes */}
              <Button
                className="w-full h-10 text-sm font-medium"
                size="md"
                variant="outline"
                onClick={handleCopyNotes}
                leftIcon={copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
              >
                {copied ? 'Copied to Clipboard!' : 'Copy to Learning Notes'}
              </Button>
            </>
          ) : (
            <>
              <Button
                className="w-full h-12 text-base shadow-brand-500/20 shadow-lg font-semibold tracking-wide"
                size="lg"
                variant="primary"
                disabled={!selectedStepId}
                onClick={() => selectedStep && onContinue(selectedStep)}
                leftIcon={<ArrowRight className="w-5 h-5" />}
              >
                {selectedStep ? `Continue: ${selectedStep.ctaText}` : "Select a step to continue"}
              </Button>
              {/* Copy to Learning Notes - also available when not mastered */}
              <Button
                className="w-full h-10 text-sm font-medium"
                size="md"
                variant="outline"
                onClick={handleCopyNotes}
                leftIcon={copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
              >
                {copied ? 'Copied to Clipboard!' : 'Copy to Learning Notes'}
              </Button>
            </>
          )}
        </div>
      </div>
    </div>
  );
};